# ${project.name} - ${project.description}
# 项目地址: ${project.url}
# 下载地址: ${project.distributionManagement.downloadUrl}
version: ${project.version}
debug: false

# 统计数据设定
# 该选项用于帮助开发者统计插件版本与使用情况，且绝不会影响性能与使用体验。
# 当然，您也可以选择在这里关闭，或在plugins/bStats下的配置文件中关闭。
metrics: true

# 检查更新设定
# 该选项用于插件判断是否要检查更新，若您不希望插件检查更新并提示您，可以选择关闭。
# 检查更新为异步操作，绝不会影响性能与使用体验。
check-update: true

# 存储相关配置
# 注意：存储配置不会通过重载指令生效，如有修改请重新启动服务器。
storage:

  # 存储方式，可选 [ yaml | json | mysql | Essential(须安装ess插件) ]
  method: yaml

  # 选择 yaml/json 存储方式时的存储路径
  # 默认为相对路径，相对于插件生成的配置文件夹下的路径
  # 支持绝对路径，如 “/var/data/moe-teleport/"(linux) 或 "D:\data\moe-teleport\"(windows)
  # 使用绝对路径时请注意权限问题
  file-path: data

  # 选择 database 存储方式时的数据库配置
  mysql:
    # 数据库驱动路径
    driver: "com.mysql.cj.jdbc.Driver"
    # 数据库连接配置
    host: "127.0.0.1"
    port: 3306
    database: "minecraft"
    username: "username"
    password: "password"
    # 插件相关表的名称
    tables:
      last-location: "mt_last_locations"
      home: "mt_homes"
      warps: "mt_warps"


defaults:
  # 默认玩家可设置多少家
  home: 1
  # 默认玩家可设置多少地标
  warp: 0

permissions:
  home:
    10: "MoeTeleport.home.vip" # 拥有该权限的玩家最多可以设置10个家
  warp:
    2: "MoeTeleport.home.vip" # 拥有该权限的玩家最多可以设置2个地标

# 传送请求过期时间
expireTime: 30

# 返回死亡点
# 开启后将允许玩家输入 /back 返回死亡地点。
death-back: true

# 危险的方块类型，将判断目的地脚下的方块的类型是否在这个列表中
dangerous-blocks:
  - LAVA
  - AIR
