version: ${project.version}

defaultHome: 1

permissions:
  # 以下命令全部为 MoeTeleport 的子节点
  # 如 "home.1" 的权限全拼就是 "MoeTeleport.home.1"
  "home.1": 1 # 代表最多可以设置一个家
  "home.vip": 10 # 最多可以设置10个家

# 传送请求过期时间
expireTime: 30

# 危险的方块类型，将判断目的地脚下的方块的类型是否在这个列表中
dangerousBlocks:
  - LAVA
  - AIR