version: ${project.version}

defaultHome: 1

permissions:
  # 以下命令全部为 MoeTeleport 的子节点
  # 如 "home.1" 的权限全拼就是 "MoeTeleport.home.1"
  "home.1": 1 # 代表最多可以设置一个家
  "home.vip": 10 # 最多可以设置10个家

messages:
  tpa:
    - "&6%(player) &f请求传送到您身边，您可以在30秒内输入 &e/tpaccept &f同意该请求。"
  tpahere:
    - "&6%(player) &f请求传送您到Ta身边，您可以在30秒内输入 &e/tpaccept &f同意该请求。"
  tpaccept:
    - "&f您同意了 &6%(player) &f的传送请求。"
  tpadeny:
    - "&f您&c拒绝&f了 &6%(player) &f的传送请求。"
  accepted:
    - "&6%(player) &f同意了您的传送请求。"
  denied:
    - "&6%(player) &c拒绝&f了您的传送请求。"

  no-request:
    - "&f您当前没有任何待处理的传送请求。"
  no-request-player:
    - "&f您当前没有收到来自 &6%(player) &f的传送请求。"
  multi-requests:
    - "&f您当前有条请求待处理，请输入 &6/tpaccept <玩家名> &f决定同意谁的请求。"
    - "&f您也可以再次输入 &6/tpaccept &f直接同意最近的一条请求。"
  request-timeout:
    - "&f来自 &6%(player) &f的传送请求已超时。"
  teleporting:
    - "&f正在传送到 &6&(location) &f..."
  dangerous:
    - "&f目标地点不安全，传送被取消。若您质疑传送可再次输入 &6/tpaccept &f。"

  home-list-header:
    - "&f您当前设定的所有家："
  home-list-object: "&8#&f%(id) &6(location)"