main: cc.carm.plugin.moeteleport.Main
name: MoeTeleport
version: ${project.version}
author: CarmJos
website: ${project.url}
description: ${project.description}

api-version: 1.13

softdepend:
  - PlaceholderAPI
  - Essentials
  - CMI

permissions:
  "MoeTeleport":
    description: "插件的主权限节点"
    default: false

  "MoeTeleport.admin":
    description: "插件的管理员权限节点"
    default: op

commands:
  "MoeTeleport":
    description: "插件的主命令，用于重载插件或查看插件信息。"
    permission: "MoeTeleport.admin"
    usage: "/MoeTeleport reload"

  "back":
    description: 返回传送前的上一个地点。

  "tpa":
    usage: "/tpa <玩家> "
    description: 请求传送到一个玩家身边。
  "tpaHere":
    usage: "/tpaHere <玩家>"
    description: 请求一个玩家传送到自己身边。
  "tpAccept":
    usage: "/tpAccept [玩家]"
    description: 同意一个请求，可以限定某个玩家。
  "tpDeny":
    usage: "/tpDeny [玩家]"
    description: 拒绝一个请求，可以限定某个玩家。

  "home":
    usage: "/home [名称] "
    description: "返回家所在位置。"
  "listHome":
    description: "列出所有家的位置。"
  "setHome":
    usage: "/setHome [名称] "
    description: "设置家的传送点 (不填名称默认为home)"
  "delHome":
    usage: "/delHome <名称> "
    description: "删除家的传送点。"

  "warp":
    usage: "/warp [名称] "
    description: "返回地标点所在位置。"
  "warpInfo":
    usage: "/warpInfo <名称> "
    description: "查看地标点相关信息。"
  "listWarps":
    aliases:
      - warps
    usage: “/listWarps [页码]”
    description: "列出服务器中所有地标点位置。"
  "setWarp":
    usage: "/setWarp [名称] "
    description: "设置地标传送点 (不填名称默认为自己的游戏ID)"
  "delWarp":
    usage: "/delWarp <名称> "
    description: "删除一个地标传送点。"