main: cc.carm.plugin.moeteleport.Main
name: MoeTeleport
version: ${project.version}
author: CarmJos
website: ${project.url}
description: ${project.description}

api-version: 1.13

softdepend:
  - PlaceholderAPI
  - Essentials
  - CMI

permissions:

  "MoeTeleport.admin":
    description: "插件的管理员权限节点"
    default: op

  "MoeTeleport.teleport":
    description: "使用传送请求相关指令的权限。"
    default: true

  "MoeTeleport.home":
    description: "使用家相关指令的权限。"
    default: true

  "MoeTeleport.warp":
    description: "使用传送请求相关指令的权限。"
    default: true

  "MoeTeleport.back":
    description: "使用返回相关指令的权限。"
    default: true

commands:
  "MoeTeleport":
    description: "插件的主命令，用于重载插件或查看插件信息。"
    usage: "您可以输入 /MoeTeleport help 查看插件的相关帮助。"
    aliases:
      - mt