main: cc.carm.plugin.moeteleport.Main
name: MoeTeleport
version: ${project.version}
author: CarmJos
website: ${project.url}
description: ${project.description}

api-version: 1.13

softdepend:
  - PlaceholderAPI
  - Essentials
  - CMI

permissions:
  "MoeTeleport":
    description: "插件的主权限节点"
    default: false

  "MoeTeleport.admin":
    description: "插件的管理员权限节点"
    default: op

commands:
  "MoeTeleport":
    description: "插件的主命令，用于重载插件或查看插件信息。"
    permission: "MoeTeleport.admin"
    usage: "/MoeTeleport reload"